PRMT-1233 - Introduce plan_dev pipeline state

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -4,26 +4,35 @@ set -Eeo pipefail
 ENVIRONMENT=dev
 STACK=data-pipeline
 
+function tf_init {
+    terraform init -backend-config key=${ENVIRONMENT}/${STACK}/terraform.tfstate
+}
+
 for command in "$@"
 do
-  echo "--- ${command} ---"
-  case "${command}" in
-      validate)
-          cd terraform
-          terraform init -backend-config key=${ENVIRONMENT}/${STACK}/terraform.tfstate
-          terraform validate
-          ;;
-      print-test)
-          echo "apple"
-          ;;
-      dojo-validate)
-          dojo "./tasks validate"
-          ;;
-      *)
-          echo "Invalid command: '${command}'"
-          exit 1
-          ;;
-  esac
+    echo "--- ${command} ---"
+    case "${command}" in
+        validate)
+            cd terraform
+            tf_init
+            terraform validate
+        ;;
+        dojo-validate)
+            dojo "./tasks validate"
+        ;;
+        plan)
+            cd terraform
+            tf_init
+            terraform plan -out=dev.tfplan
+        ;;
+        dojo-plan)
+            dojo "./tasks plan"
+        ;;
+        *)
+            echo "Invalid command: '${command}'"
+            exit 1
+        ;;
+    esac
 done
 
 set +e
