PRMT-1233 - [MP/JG/HZ] Allow stack environment to be supplied to tasks as an argument

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -2,45 +2,50 @@
 
 set -Eeo pipefail
 
-stack_env=dev
 stack_name=data-pipeline
 tf_dir=terraform
 
 function tf_init {
     directory=$1
+    stack_env=$2
     terraform init -backend-config key=${stack_env}/${stack_name}/terraform.tfstate ${directory}
 }
 
-for command in "$@"
-do
-    echo "--- ${command} ---"
-    case "${command}" in
-        validate)
-            tf_init ${tf_dir}
-            terraform validate ${tf_dir}
-        ;;
-        dojo-validate)
-            dojo "./tasks validate"
-        ;;
-        plan)
-            tf_init ${tf_dir}
-            terraform plan -var environment=${stack_env} -out=dev.tfplan ${tf_dir}
-        ;;
-        dojo-plan)
-            dojo "./tasks plan"
-        ;;
-        apply)
-            tf_init ${tf_dir}
-            terraform apply dev.tfplan
-        ;;
-        dojo-apply)
-            dojo "./tasks apply"
-        ;;
-        *)
-            echo "Invalid command: '${command}'"
-            exit 1
-        ;;
-    esac
-done
+if [ "$#" -ne 2 ]; then
+    echo "Usage: $0 TASK STACK-ENVIRONMENT"
+    exit 1
+fi
+
+task="$1"
+stack_env="$2"
+
+echo "--- ${task} ---"
+case "${task}" in
+    validate)
+        tf_init ${tf_dir} ${stack_env}
+        terraform validate ${tf_dir}
+    ;;
+    dojo-validate)
+        dojo "./tasks validate ${stack_env}"
+    ;;
+    plan)
+        tf_init ${tf_dir} ${stack_env}
+        terraform plan -var environment=${stack_env} -out=${stack_env}.tfplan ${tf_dir}
+    ;;
+    dojo-plan)
+        dojo "./tasks plan ${stack_env}"
+    ;;
+    apply)
+        tf_init ${tf_dir}
+        terraform apply ${stack_env}.tfplan
+    ;;
+    dojo-apply)
+        dojo "./tasks apply ${stack_env}"
+    ;;
+    *)
+        echo "Invalid task: '${task}'"
+        exit 1
+    ;;
+esac
 
 set +e
